In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

# object creation
works similar to numpy arrays

In [5]:
s=pd.Series([1,3,4,np.nan,6,8])

In [6]:
s

0    1.0
1    3.0
2    4.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [7]:
s[0]

1.0

In [8]:
s[:3]

0    1.0
1    3.0
2    4.0
dtype: float64

In [9]:
s[s>2]

1    3.0
2    4.0
4    6.0
5    8.0
dtype: float64

In [10]:
np.exp(s)

0       2.718282
1      20.085537
2      54.598150
3            NaN
4     403.428793
5    2980.957987
dtype: float64

vectorized operations

In [11]:
s+s

0     2.0
1     6.0
2     8.0
3     NaN
4    12.0
5    16.0
dtype: float64

A key difference between Series and ndarray is that operations between Series automatically align the data based on label. Thus, you can write computations without giving consideration to whether the Series involved have the same labels.

In [12]:
s[1:]

1    3.0
2    4.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [13]:
s[:-1]

0    1.0
1    3.0
2    4.0
3    NaN
4    6.0
dtype: float64

In [14]:
s[1:]+s[:-1]

0     NaN
1     6.0
2     8.0
3     NaN
4    12.0
5     NaN
dtype: float64

# DataFrame

In [15]:
d={"one":pd.Series([1,2,3,4,5]),"two":pd.Series([6,7,8,9,0])}

In [16]:
d

{'one': 0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64, 'two': 0    6
 1    7
 2    8
 3    9
 4    0
 dtype: int64}

In [17]:
df = pd.DataFrame(d)

In [18]:
df

one  two
0    1    6
1    2    7
2    3    8
3    4    9
4    5    0

In [19]:
pd.DataFrame(d,index=[3,4])

one  two
3    4    9
4    5    0

In [20]:
pd.DataFrame(d,index=[0,1,2],columns=["one","two","three"])

one  two three
0    1    6   NaN
1    2    7   NaN
2    3    8   NaN

# Assigning New Columns in Method Chains

In [21]:
salary = pd.read_csv("../matplotlib/pdacookbook-master/data/mlbsalaries.csv")

In [22]:
salary.head()

Year           Player   Salary           Position                Team
0  1988        Mike Witt  1400000            Pitcher  Los Angeles Angels
1  1988  George Hendrick   989333         Outfielder  Los Angeles Angels
2  1988      Chili Davis   950000         Outfielder  Los Angeles Angels
3  1988    Brian Downing   900000  Designated Hitter  Los Angeles Angels
4  1988        Bob Boone   883000            Catcher  Los Angeles Angels

In [23]:
salary.assign(Salary2=salary["Salary"]**2).head()

Year           Player   Salary           Position                Team  \
0  1988        Mike Witt  1400000            Pitcher  Los Angeles Angels   
1  1988  George Hendrick   989333         Outfielder  Los Angeles Angels   
2  1988      Chili Davis   950000         Outfielder  Los Angeles Angels   
3  1988    Brian Downing   900000  Designated Hitter  Los Angeles Angels   
4  1988        Bob Boone   883000            Catcher  Los Angeles Angels   

         Salary2  
0  1960000000000  
1   978779784889  
2   902500000000  
3   810000000000  
4   779689000000

In [24]:
salary.assign(Salary2 = lambda x: (x["Salary"]**2)  ).head()

Year           Player   Salary           Position                Team  \
0  1988        Mike Witt  1400000            Pitcher  Los Angeles Angels   
1  1988  George Hendrick   989333         Outfielder  Los Angeles Angels   
2  1988      Chili Davis   950000         Outfielder  Los Angeles Angels   
3  1988    Brian Downing   900000  Designated Hitter  Los Angeles Angels   
4  1988        Bob Boone   883000            Catcher  Los Angeles Angels   

         Salary2  
0  1960000000000  
1   978779784889  
2   902500000000  
3   810000000000  
4   779689000000

In [25]:
salary.loc(0)

In [26]:
salary.iloc[0]

Year                      1988
Player               Mike Witt
Salary                 1400000
Position               Pitcher
Team        Los Angeles Angels
Name: 0, dtype: object

# Data alignment

In [27]:
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])

In [28]:
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])

In [29]:
df

A         B         C         D
0 -0.314816  0.618365  0.724681 -1.217419
1 -0.212516  0.427708 -1.868359  0.753414
2  0.641336  0.012461 -1.441428 -0.684278
3 -1.027784 -0.423013  3.793856  0.243322
4  0.445849 -0.707574 -0.800030  0.631951
5  0.315941 -0.922866 -0.120274 -0.243464
6  0.909241  2.695134 -0.043851  0.473565
7  0.425132 -0.648624  1.358992 -0.454103
8  0.232361  0.494414 -0.413041 -0.349063
9 -0.535290 -1.331755 -0.331243 -1.368193

In [30]:
df2

A         B         C
0  1.190199 -1.476158  0.030088
1 -1.155482 -1.437337  0.847484
2 -0.750188  1.074514 -0.335380
3  0.118606  1.357110  0.955275
4  1.165292 -0.345356  3.008598
5  0.039451 -0.714598  1.450564
6  0.355616  1.676021 -0.303800

In [31]:
df+df2

A         B         C   D
0  0.875383 -0.857793  0.754769 NaN
1 -1.367999 -1.009629 -1.020875 NaN
2 -0.108852  1.086975 -1.776807 NaN
3 -0.909178  0.934097  4.749131 NaN
4  1.611141 -1.052930  2.208568 NaN
5  0.355392 -1.637464  1.330291 NaN
6  1.264857  4.371154 -0.347650 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [32]:
df-df.iloc[1]

A         B         C         D
0 -0.102300  0.190657  2.593041 -1.970833
1  0.000000  0.000000  0.000000  0.000000
2  0.853852 -0.415247  0.426932 -1.437692
3 -0.815267 -0.850721  5.662215 -0.510091
4  0.658365 -1.135282  1.068329 -0.121463
5  0.528457 -1.350574  1.748086 -0.996878
6  1.121757  2.267426  1.824509 -0.279848
7  0.637648 -1.076333  3.227351 -1.207517
8  0.444877  0.066706  1.455319 -1.102476
9 -0.322774 -1.759463  1.537117 -2.121607

In [33]:
df["A"]

0   -0.314816
1   -0.212516
2    0.641336
3   -1.027784
4    0.445849
5    0.315941
6    0.909241
7    0.425132
8    0.232361
9   -0.535290
Name: A, dtype: float64

In [34]:
df-df["A"]

0   1   2   3   4   5   6   7   8   9   A   B   C   D
0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
5 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
6 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
7 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
8 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
9 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [35]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19543 entries, 0 to 19542
Data columns (total 5 columns):
Year        19543 non-null int64
Player      19543 non-null object
Salary      19543 non-null int64
Position    19543 non-null object
Team        19543 non-null object
dtypes: int64(2), object(3)
memory usage: 763.5+ KB


In [36]:
salary.Salary

0         1400000
1          989333
2          950000
3          900000
4          883000
5          857000
6          785000
7          733333
8          552222
9          525000
10         425000
11         340000
12         262000
13         200000
14         185000
15         125000
16         122500
17         111000
18         107500
19          97000
20          70000
21          62500
22          62500
23          62500
24          62500
25          62500
26        1200000
27        1100000
28        1025000
29         950000
           ...   
19513    32000000
19514    24285714
19515    23125000
19516    16500000
19517    14911700
19518    14729364
19519    13100000
19520    10000000
19521    10000000
19522     9100000
19523     8250000
19524     4000000
19525     4000000
19526     3750000
19527     2700000
19528     1500000
19529     1500000
19530     1500000
19531     1400000
19532     1200000
19533      900000
19534      650000
19535      529500
19536      460450
19537     

In [37]:
df-df.A

0   1   2   3   4   5   6   7   8   9   A   B   C   D
0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
5 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
6 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
7 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
8 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
9 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

DataFrame by passing a numpy array

In [38]:
dates = pd.date_range('20130101', periods=6)

In [39]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [40]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [41]:
df

A         B         C         D
2013-01-01  1.376152 -1.741157  0.192638 -0.118999
2013-01-02  0.761967  0.473411 -0.826658 -0.395458
2013-01-03  0.517021 -0.156804  0.168333  2.559667
2013-01-04  2.581764  1.301929 -0.194203 -1.526037
2013-01-05  0.288676  0.528978  0.371846  0.753290
2013-01-06  0.612486  1.380763  0.092525  0.485250

# Viewing Data

top

In [42]:
df.head()

A         B         C         D
2013-01-01  1.376152 -1.741157  0.192638 -0.118999
2013-01-02  0.761967  0.473411 -0.826658 -0.395458
2013-01-03  0.517021 -0.156804  0.168333  2.559667
2013-01-04  2.581764  1.301929 -0.194203 -1.526037
2013-01-05  0.288676  0.528978  0.371846  0.753290

bottom

In [43]:
df.tail()

A         B         C         D
2013-01-02  0.761967  0.473411 -0.826658 -0.395458
2013-01-03  0.517021 -0.156804  0.168333  2.559667
2013-01-04  2.581764  1.301929 -0.194203 -1.526037
2013-01-05  0.288676  0.528978  0.371846  0.753290
2013-01-06  0.612486  1.380763  0.092525  0.485250

In [44]:
print df.index, df.columns, df.values

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D') Index([u'A', u'B', u'C', u'D'], dtype='object') [[ 1.37615176 -1.74115707  0.19263793 -0.11899851]
 [ 0.76196719  0.47341131 -0.82665775 -0.39545828]
 [ 0.51702109 -0.15680371  0.16833282  2.55966689]
 [ 2.5817636   1.30192867 -0.19420316 -1.52603674]
 [ 0.28867603  0.52897752  0.37184562  0.75328993]
 [ 0.6124857   1.38076325  0.09252459  0.48524987]]


In [45]:
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

quick statistic summary of your data

In [46]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   1.023011  0.297853 -0.032587  0.292952
std    0.846920  1.151467  0.430577  1.366691
min    0.288676 -1.741157 -0.826658 -1.526037
25%    0.540887  0.000750 -0.122521 -0.326343
50%    0.687226  0.501194  0.130429  0.183126
75%    1.222606  1.108691  0.186562  0.686280
max    2.581764  1.380763  0.371846  2.559667

In [47]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.118999  0.192638 -1.741157  1.376152
2013-01-02 -0.395458 -0.826658  0.473411  0.761967
2013-01-03  2.559667  0.168333 -0.156804  0.517021
2013-01-04 -1.526037 -0.194203  1.301929  2.581764
2013-01-05  0.753290  0.371846  0.528978  0.288676
2013-01-06  0.485250  0.092525  1.380763  0.612486

In [48]:
df.sort_values(by='B')

A         B         C         D
2013-01-01  1.376152 -1.741157  0.192638 -0.118999
2013-01-03  0.517021 -0.156804  0.168333  2.559667
2013-01-02  0.761967  0.473411 -0.826658 -0.395458
2013-01-05  0.288676  0.528978  0.371846  0.753290
2013-01-04  2.581764  1.301929 -0.194203 -1.526037
2013-01-06  0.612486  1.380763  0.092525  0.485250

In [49]:
df.loc[:,['A','C']]

A         C
2013-01-01  1.376152  0.192638
2013-01-02  0.761967 -0.826658
2013-01-03  0.517021  0.168333
2013-01-04  2.581764 -0.194203
2013-01-05  0.288676  0.371846
2013-01-06  0.612486  0.092525

In [50]:
df.loc['20130102':'20130104',['A','B']]

A         B
2013-01-02  0.761967  0.473411
2013-01-03  0.517021 -0.156804
2013-01-04  2.581764  1.301929

In [51]:
df.loc[dates[0],'A']

1.376151759748514

In [52]:
df.at[dates[0],'A']

1.376151759748514

# Filtering

In [53]:
df2 = df.copy()

In [54]:
df2['E'] = ['one', 'one','two','three','four','three']

In [55]:
df2

A         B         C         D      E
2013-01-01  1.376152 -1.741157  0.192638 -0.118999    one
2013-01-02  0.761967  0.473411 -0.826658 -0.395458    one
2013-01-03  0.517021 -0.156804  0.168333  2.559667    two
2013-01-04  2.581764  1.301929 -0.194203 -1.526037  three
2013-01-05  0.288676  0.528978  0.371846  0.753290   four
2013-01-06  0.612486  1.380763  0.092525  0.485250  three

In [56]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  0.517021 -0.156804  0.168333  2.559667   two
2013-01-05  0.288676  0.528978  0.371846  0.753290  four

In [57]:
df2[df2["D"]>0]

A         B         C         D      E
2013-01-03  0.517021 -0.156804  0.168333  2.559667    two
2013-01-05  0.288676  0.528978  0.371846  0.753290   four
2013-01-06  0.612486  1.380763  0.092525  0.485250  three

In [58]:
df

A         B         C         D
2013-01-01  1.376152 -1.741157  0.192638 -0.118999
2013-01-02  0.761967  0.473411 -0.826658 -0.395458
2013-01-03  0.517021 -0.156804  0.168333  2.559667
2013-01-04  2.581764  1.301929 -0.194203 -1.526037
2013-01-05  0.288676  0.528978  0.371846  0.753290
2013-01-06  0.612486  1.380763  0.092525  0.485250

In [59]:
df.loc[:,'D'] = np.array([5] * len(df))

In [60]:
df

A         B         C  D
2013-01-01  1.376152 -1.741157  0.192638  5
2013-01-02  0.761967  0.473411 -0.826658  5
2013-01-03  0.517021 -0.156804  0.168333  5
2013-01-04  2.581764  1.301929 -0.194203  5
2013-01-05  0.288676  0.528978  0.371846  5
2013-01-06  0.612486  1.380763  0.092525  5

In [61]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))

In [62]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [63]:
df['F'] = s1

In [64]:
df

A         B         C  D    F
2013-01-01  1.376152 -1.741157  0.192638  5  NaN
2013-01-02  0.761967  0.473411 -0.826658  5  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0
2013-01-04  2.581764  1.301929 -0.194203  5  3.0
2013-01-05  0.288676  0.528978  0.371846  5  4.0
2013-01-06  0.612486  1.380763  0.092525  5  5.0

Reindexing allows you to change/add/delete the index on a specified axis.

In [65]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])

In [66]:
df1

A         B         C  D    F   E
2013-01-01  1.376152 -1.741157  0.192638  5  NaN NaN
2013-01-02  0.761967  0.473411 -0.826658  5  1.0 NaN
2013-01-03  0.517021 -0.156804  0.168333  5  2.0 NaN
2013-01-04  2.581764  1.301929 -0.194203  5  3.0 NaN

In [67]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [68]:
df1

A         B         C  D    F    E
2013-01-01  1.376152 -1.741157  0.192638  5  NaN  1.0
2013-01-02  0.761967  0.473411 -0.826658  5  1.0  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0  NaN
2013-01-04  2.581764  1.301929 -0.194203  5  3.0  NaN

To drop any rows that have missing data.

In [69]:
df1.dropna(how='any')

A         B         C  D    F    E
2013-01-02  0.761967  0.473411 -0.826658  5  1.0  1.0

In [70]:
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  1.376152 -1.741157  0.192638  5  5.0  1.0
2013-01-02  0.761967  0.473411 -0.826658  5  1.0  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0  5.0
2013-01-04  2.581764  1.301929 -0.194203  5  3.0  5.0

To get the boolean mask where values are nan

In [71]:
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

# Operations

In [72]:
df.mean()

A    1.023011
B    0.297853
C   -0.032587
D    5.000000
F    3.000000
dtype: float64

In [73]:
df.mean(1)

2013-01-01    1.206908
2013-01-02    1.281744
2013-01-03    1.505710
2013-01-04    2.337898
2013-01-05    2.037900
2013-01-06    2.417155
Freq: D, dtype: float64

Applying functions to the data

In [76]:
df.apply(np.cumsum),df

(                   A         B         C   D     F
 2013-01-01  1.376152 -1.741157  0.192638   5   NaN
 2013-01-02  2.138119 -1.267746 -0.634020  10   1.0
 2013-01-03  2.655140 -1.424549 -0.465687  15   3.0
 2013-01-04  5.236904 -0.122621 -0.659890  20   6.0
 2013-01-05  5.525580  0.406357 -0.288045  25  10.0
 2013-01-06  6.138065  1.787120 -0.195520  30  15.0,
                    A         B         C  D    F
 2013-01-01  1.376152 -1.741157  0.192638  5  NaN
 2013-01-02  0.761967  0.473411 -0.826658  5  1.0
 2013-01-03  0.517021 -0.156804  0.168333  5  2.0
 2013-01-04  2.581764  1.301929 -0.194203  5  3.0
 2013-01-05  0.288676  0.528978  0.371846  5  4.0
 2013-01-06  0.612486  1.380763  0.092525  5  5.0)

In [75]:
df

A         B         C  D    F
2013-01-01  1.376152 -1.741157  0.192638  5  NaN
2013-01-02  0.761967  0.473411 -0.826658  5  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0
2013-01-04  2.581764  1.301929 -0.194203  5  3.0
2013-01-05  0.288676  0.528978  0.371846  5  4.0
2013-01-06  0.612486  1.380763  0.092525  5  5.0

In [77]:
df.apply(lambda x: x.max() - x.min())

A    2.293088
B    3.121920
C    1.198503
D    0.000000
F    4.000000
dtype: float64

Histogramming

In [78]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [79]:
s

0    4
1    5
2    6
3    3
4    0
5    3
6    6
7    1
8    5
9    6
dtype: int64

In [80]:
s.value_counts()

6    3
5    2
3    2
4    1
1    1
0    1
dtype: int64

# I/O data

In [81]:
df.to_hdf('foo.h5','df')

In [82]:
df.to_csv('foo.csv')

In [83]:
df.to_excel('foo.xlsx', sheet_name='Sheet1')

In [84]:
pd.read_hdf('foo.h5','df')

A         B         C  D    F
2013-01-01  1.376152 -1.741157  0.192638  5  NaN
2013-01-02  0.761967  0.473411 -0.826658  5  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0
2013-01-04  2.581764  1.301929 -0.194203  5  3.0
2013-01-05  0.288676  0.528978  0.371846  5  4.0
2013-01-06  0.612486  1.380763  0.092525  5  5.0

In [85]:
pd.read_csv('foo.csv')

Unnamed: 0         A         B         C  D    F
0  2013-01-01  1.376152 -1.741157  0.192638  5  NaN
1  2013-01-02  0.761967  0.473411 -0.826658  5  1.0
2  2013-01-03  0.517021 -0.156804  0.168333  5  2.0
3  2013-01-04  2.581764  1.301929 -0.194203  5  3.0
4  2013-01-05  0.288676  0.528978  0.371846  5  4.0
5  2013-01-06  0.612486  1.380763  0.092525  5  5.0

In [86]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

A         B         C  D    F
2013-01-01  1.376152 -1.741157  0.192638  5  NaN
2013-01-02  0.761967  0.473411 -0.826658  5  1.0
2013-01-03  0.517021 -0.156804  0.168333  5  2.0
2013-01-04  2.581764  1.301929 -0.194203  5  3.0
2013-01-05  0.288676  0.528978  0.371846  5  4.0
2013-01-06  0.612486  1.380763  0.092525  5  5.0